red1:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  kinect_state_controller:
    type: effort_controllers/JointPositionController
    joint: camera_joint
    pid: {p: 1.0, i: 1.0, d: 0.0 }

