# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
kinect_position_controller:
  type: effort_controllers/JointPositionController
  joint: camera_joint
  pid: {p: 3.0, i: 0.5, d: 1.0}