shutdown_costmaps: true
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 6.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 2.0
oscillation_distance: 0.2
